name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy-abstractions:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    with:
        dotnet-version: '5.0.x' # SDK Version to use.
        source-url: https://nuget.pkg.github.com/garrettleach/index.json
    env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: dotnet build --configuration Release src/DiscordDotNet.Abstractions
    - run: dotnet build --configuration Release src/DiscordDotNet
    - name: Create the Abstractions package
    run: dotnet pack --configuration Release src/DiscordDotNet.Abstractions
    - name: Create the Implementation package
    run: dotnet pack --configuration Release src/DiscordDotNet
    - name: Publish the packages to GPR
    run: dotnet nuget push src/DiscordDotNet**/bin/Release/*.nupkg